### ISSUE TITLE
equation is wrong

### ISSUE THREAD

**Issue by maria-lojowska** [maria-lojowska/practicegithub2#2]
the equation is wrong in this code below. Can you fix it?

https://github.com/maria-lojowska/practicegithub2/commit/567bc22184b287505a76e9c8e4a525b67d29ef33

**Comment by soowa** [comment]
Sure, can you help me with what the proper equation should be?

**Comment by maria-lojowska** [comment]
it should be: c -> a-b

**Comment by soowa** [comment]
Fixed it in commit https://github.com/maria-lojowska/practicegithub2/commit/34b24a6a12a8fe368305314886364dbf0217f60d
